### ISSUE TITLE
【Android】作品やプロフィールの画像がアップできない

### ISSUE THREAD

**Issue by jannbmsy** [todoroki00/sakigake03_src#74]
作品
![screenshot_2017-03-05-15-25-01](https://cloud.githubusercontent.com/assets/11519515/23585197/7a196c3c-01bb-11e7-8bf9-e04aa4b7f4f6.jpg)

プロフィール
![screenshot_2017-03-05-15-37-51](https://cloud.githubusercontent.com/assets/11519515/23585199/7accbe2c-01bb-11e7-92c1-06f80eb3db11.jpg)

アップ後に見えるスクショ
![screenshot_2017-03-05-15-26-02](https://cloud.githubusercontent.com/assets/11519515/23585201/7dfb4ac8-01bb-11e7-8030-9e2c1315c9dd.jpg)

アップしようとした画像
![img_20170305_153712](https://cloud.githubusercontent.com/assets/11519515/23585202/7f62a1cc-01bb-11e7-83ea-87d14df85604.jpg)

**Comment by HiroyukiYahagi** [comment]
ionic pluginで自動生成されるrequest headerの値が異なってた。
