### ISSUE TITLE
【Android】作品へのコメントが「1」[]

### ISSUE THREAD

**Issue by jannbmsy** [todoroki00/sakigake03_src#75]
おそらくコメント数が表示されている
「1」「2」と表示されている
![screenshot_2017-03-05-15-53-44](https://cloud.githubusercontent.com/assets/11519515/23585244/4f63964c-01bc-11e7-98fe-056642b83b38.jpg)

数字部分をクリックするとコメントが表示・コメントできる
また、コメントした人の名前が表示されていない。

![screenshot_2017-03-05-15-54-06](https://cloud.githubusercontent.com/assets/11519515/23585245/5050313c-01bc-11e7-90e3-7c89602fb1bb.jpg)

**Comment by HiroyukiYahagi** [comment]
ion-icon text-outlineがandroid対応してなかた
